ekf_localization:
  frequency: 50.0
  sensor_timeout: 1.0
  two_d_mode: false
  publish_tf: true
  publish_acceleration: false
  use_control: false
  control_timeout: 0.2
  acceleration_limits: [0.5, 0.5, 0.5]
  acceleration_noise: [0.1, 0.1, 0.1]
  process_noise_covariance:
    - 0.01 0.0 0.0 0.0 0.0 0.0
    - 0.0 0.01 0.0 0.0 0.0 0.0
    - 0.0 0.0 0.01 0.0 0.0 0.0
    - 0.0 0.0 0.0 0.01 0.0 0.0
    - 0.0 0.0 0.0 0.0 0.01 0.0
    - 0.0 0.0 0.0 0.0 0.0 0.01
  initial_state_covariance:
    - 1.0 0.0 0.0 0.0 0.0 0.0
    - 0.0 1.0 0.0 0.0 0.0 0.0
    - 0.0 0.0 1.0 0.0 0.0 0.0
    - 0.0 0.0 0.0 1.0 0.0 0.0
    - 0.0 0.0 0.0 0.0 1.0 0.0
    - 0.0 0.0 0.0 0.0 0.0 1.0
  use_gps: true
  gps0_queue_size: 10
  gps0: /mavros/global_position/global
  imu0: /mavros/imu/data
  imu0_queue_size: 10
